name: AbuseLogger
version: 1.0.0
main: com.uxplima.abuselogger.AbuseLogger
api-version: '1.21'
depend: [uxmClaims]
author: MCVadisi
description: uxmClaims Abuse-Log eklentisi
commands:
  abuselogger:
    description: Main command for AbuseLogger
    permission: abuse.logger.admin
    usage: /abuselogger <reload|alerts|info>
permissions:
  abuse.logger.admin:
    description: Admin permission for AbuseLogger
    default: op
  abuse.logger.player:
    description: Player permission for claim notifications
    default: false
  abuse.logger.toggle:
    description: Permission to toggle alerts
    default: true
