name: AbuseLogger
version: '1.0.0'
main: com.furkan.abuselogger.AbuseLogger
api-version: '1.21'
description: "Abuse Logger Plugin"
dependencies:
  server:
    uxmClaims:
      load: BEFORE
      required: true
